import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('suggestion form is a closed disclosure tied to the current meeting', async () => {
  const source = await readFile('js/vote.js', 'utf8');
  const css = await readFile('css/style.css', 'utf8');

  assert.match(source, /function roundLabel/);
  assert.match(source, /function roundNumberText/);
  assert.match(source, /function roundTitleExtra/);
  assert.match(source, /function meetingBadge/);
  assert.match(source, /function roundHero/);
  assert.match(source, /function authPanel/);
  assert.match(source, /function canParticipate/);
  assert.match(source, /function nextDateDetail/);
  assert.match(source, /vote-meeting/);
  assert.match(source, /vote-meeting-number/);
  assert.match(source, /vote-ritual-hero/);
  assert.match(source, /vote-timeline-section/);
  assert.match(source, /vote-disclosure/);
  assert.match(source, /'aria-expanded': 'false'/);
  assert.match(source, /panel\.hidden = true/);
  assert.match(source, /function renderSuggestionList/);
  assert.match(source, /function addApprovedSuggestion/);
  assert.match(source, /if \(!res\.pending\) addApprovedSuggestion\(res\.game\)/);
  assert.match(source, /Foresl/);
  assert.match(source, /Suggest new game/);
  assert.doesNotMatch(source, /sendt til godkendelse/);
  assert.doesNotMatch(source, /sent for approval/);
  assert.match(source, /forslagene/);
  assert.match(source, /added to the suggestions/);
  assert.match(source, /meetingBadge[\s\S]*vote-meeting-number/);
  assert.doesNotMatch(source, /meetingFor/);
  assert.match(source, /roundLayout[\s\S]*roundHero\(round\)/);
  assert.match(source, /renderVoting[\s\S]*roundLayout\(data\.round/);
  assert.match(source, /api\('\/auth\/session'\)/);
  assert.match(source, /renderVoting[\s\S]*authPanel\('vote'\)/);
  assert.doesNotMatch(source, /turnstile/i);
  assert.doesNotMatch(source, /stormCode/);
  assert.doesNotMatch(source, /ballotId: storedVote/);
  assert.match(source, /renderRevealed[\s\S]*roundLayout\(data\.round/);

  assert.match(css, /\.vote-round-hero/);
  assert.match(css, /\.vote-ritual-hero/);
  assert.match(css, /\.vote-timeline-section/);
  assert.match(css, /\.vote-date-card/);
  assert.match(css, /\.vote-meeting/);
  assert.match(css, /\.vote-meeting-number/);
  assert.match(css, /\.vote-disclosure/);
  assert.match(css, /\.vote-disclosure-chevron/);
  assert.match(css, /\.vote-auth/);
});
